### ISSUE TITLE
Show multiple datasets.

### ISSUE THREAD

**Issue by biglebomb** [pandameister/chartjs-chart-radial-gauge#15]
Hi, is it possible to draw multiple datasets as shown in the example below?

![radial chart](https://user-images.githubusercontent.com/20764699/111058039-4f0f7d80-84be-11eb-976a-0daa3b4c4cdf.png)

**Comment by biglebomb** [comment]
Okay so it seems, the chart is already drawing all the datasets, but the track is being drawn after each dataset instead of being drawn once at the very last, resulting in the second dataset being invisible. This is just my assumption as I do not know how to debug canvas.

![image](https://user-images.githubusercontent.com/20764699/111065078-5ea4bb80-84ea-11eb-9ea8-fa8a8bb658c3.png)

**Comment by pandameister** [comment]
@biglebomb  multiple data sets are not really supported right now, but as a workaround you can use 'rgba' colors for the track and datasets so that all are visible at the same time, eg:

```js
datasets: [
            {
              data: [50],
              backgroundColor: ['rgba(200,200,200,0.5)'],
              borderWidth: 0,
              label: 'Score',
            },
            {
              data: [30],
              backgroundColor: ['rgba(20,200,290,0.5)'],
              borderWidth: 0,
              label: 'Score2',
            },
          ],
 options: {
          trackColor: 'rgba(204, 221, 238,0.1)',
}
```

**Comment by biglebomb** [comment]
Yes, it works great. Thank you. Any idea how can I implement multiple datasets like maybe a hint that I could implement it to code?

**Comment by pandameister** [comment]
@biglebomb Support for multiple datasets here probably means you want to display rings of concentric circles, one per dataset. Otherwise you will always have the overlap issue.  You can take a look at: the ` updateElement`  method in `src/controllers/controller.radialGauge.js` to see how it draws the datasets, it would then be a matter of adjusting the radius of a particular dataset based on its ordering so that it creates a ring that doesn't overlap with the other rings.
